<a href="https://colab.research.google.com/github/bornmay/Mindmap-Full-Stack/blob/master/Initial_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Importing Library**

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

**loading dataset**

In [ ]:
dataset = pd.read_csv('Data.csv')
# x is feature which is used to predict values
x = dataset.iloc[:, :-1].values # : means range in python lowerbound:upperbound (if no lower and upper select full row)
# :-1 means all columns except the last one 0 to n-1 columns 
# iloc: indexlock accepts rows / columns
# y is dependent variable used to check the output 
y = dataset.iloc[:,-1].values # -1 is index of last column.

In [ ]:
print x

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


print y

In [ ]:
print(Y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


**Taking care of Missing Data**

In [ ]:
from sklearn.impute import SimpleImputer # class SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy="mean") # all the missing vals np.nan type with mean strategy
# instance of class SimpleImputer is imputer
# we will replace the missing with most frequent (mode), average (mean) or middle value (median)
imputer.fit(X[:, 1:3]) # all rows and 2 and 3rd column cause 1st column contains the string values
# replace values in X
X[:, 1:3] = imputer.transform(X[:, 1:3]) # set all rows of column 2 and 3 with updated values in place of nan

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


**Encoding categorical data**
 
 model cant understand Germany, france so we need to encode them in diffrent pattern
 1. we can use 1 for Germany 2 for france 3 for spain, but the model will find a relation between them but there isnt any between these countries

 2. we will use random binary string for them 

encoding independent variable (oneHotEncoding)

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder="passthrough")
X = np.array(ct.fit_transform(X))
# X= ct.fit_transform(X)

In [ ]:
print(X)

[[1.0 0.0 1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 1.0 0.0 30.0 54000.0]
 [0.0 1.0 0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 1.0 0.0 0.0 37.0 67000.0]]


now france is 1.0 0.0 1.0 0.0 0.0

spain is 0.0 1.0 0.0 0.0 1.0

germany is 0.0 1.0 0.0 1.0 0.0

OneHotEncoder made 5 diffrent columns

Now we will Encode Dependent Variable from yes no to 0 and 1

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
Y = le.fit_transform(Y)

In [ ]:
print(Y)

[0 1 0 0 1 1 0 1 0 1]


splitting the dataset into Training set and Test set